### PR TITLE
fix: remove subs only when clean flag is false

### LINKED ISSUE #469: subscribe/unsubscribe processed out of order when persistence is used
When a client subscribes and unsubscribes repeatedly to the same topic in quick succession, sometimes these are processed out of order, resulting in the client believing it has subscribed but it is actually not subscribed.

It looks like the root cause is that the subscribe handler may [complete synchronously](https://github.com/moscajs/aedes/blob/295538898deaa57edcd6f62c469a55dd02a3a58c/lib/handlers/subscribe.js#L104) but the unsubscribe handler always [completes asynchronously](https://github.com/moscajs/aedes/blob/295538898deaa57edcd6f62c469a55dd02a3a58c/lib/handlers/unsubscribe.js#L30), so it's possible for the unsubscription to complete after the subscription.

As a workaround, I have implemented a modified persistence which synchronously completes the unsubscribe call when the client is "clean".

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #469

### CODE REVIEW

**Comment by robertsLando** [comment]
@mcollina ping

File: test/client-pub-sub.js [hunk 1]
```diff
@@ -514,6 +514,36 @@ test('unsubscribe a client', function (t) {
...
 })
 
+test('unsubscribe should not call removeSubscriptions when [clean=true]', function (t) {
+  t.plan(2)
+
+  const broker = aedes()
+  t.tearDown(broker.close.bind(broker))
+
+  broker.persistence.removeSubscriptions = function (client, subs, cb) {
+    cb(Error('remove subscription is called'))
```
Comment (mcollina) [inline test/client-pub-sub.js:524]: this should be a t.error instead

Comment (robertsLando) [reply test/client-pub-sub.js:524]: The error is caught by the callback of unsubscribe
